CREATE TABLE SUPERHERO_POWER (
    POWER_ID int, 
    SUPER_ID int,
    PRIMARY KEY (SUPER_ID, POWER_ID)
);

ALTER TABLE SUPERHERO_POWER
  ADD CONSTRAINT SUPER_ID FOREIGN KEY (SUPER_ID) REFERENCES SUPERHERO,
  ADD CONSTRAINT POWER_ID FOREIGN KEY (POWER_ID) REFERENCES SUPERPOWER;