INSERT INTO SUPERHERO (SUPERHERO_NAME, SUPERHERO_ALIAS, SUPERHERO_ORIGIN) VALUES ('Batman', 'Bruce Wayne', 'JADU');
INSERT INTO SUPERHERO (SUPERHERO_NAME, SUPERHERO_ALIAS, SUPERHERO_ORIGIN) VALUES ('Wonder Woman', 'Diana Prince', 'JADU');
INSERT INTO SUPERHERO (SUPERHERO_NAME, SUPERHERO_ALIAS, SUPERHERO_ORIGIN) VALUES ('Spiderman', 'Peter Parker', 'JADU');
