INSERT INTO ASSISTANT (SUPERHERO_ID, ASSISTANT_NAME) VALUES (1, 'Robin');
INSERT INTO ASSISTANT (SUPERHERO_ID, ASSISTANT_NAME) VALUES (2, 'Etta Candy');
INSERT INTO ASSISTANT (SUPERHERO_ID, ASSISTANT_NAME) VALUES (3, 'Karen');


